calls/urls.py
from django.urls import path
from calls.views import hello, index, home,  update, register, list_details, delete

app_name = 'calls'

urlpatterns = [
    path(route='hello/', view=hello, name="hello"),
    path(route='index/', view=index, name="index"),
    path(route='home/', view=home, name="home"),
    path(route='register/', view=register, name="register"),
    path(route='list/', view=list_details, name="list"),
    path(route='update/<int:pk>/', view=update, name="update"),
    path(route='delete/<int:pk>/', view=delete, name="delete"),
]

whatsapp/urls.py
from django.contrib import admin
from django.urls import path, include
from whatsapp.views import upper_case, login, about, base, sample

urlpatterns = [
    path('admin/', admin.site.urls),
    path('calls/', include('calls.urls')),
    path(route='upper/<name>/', view=upper_case, name="upper"),
    path(route='login/', view=login, name="login"),
    path(route='about/<x>/<y>/', view=about, name="about"),
    path(route='base/<data>/', view=base, name="base"),
    path(route='sample/', view=sample, name="sample"),



]

calls/models.py
from django.db import models

# Create your models here.


class personal(models.Model):
    username = models.CharField(max_length=30)
    firstname = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    email = models.EmailField(max_length=30, unique=True)
    phone = models.PositiveBigIntegerField(unique=True)
    password = models.CharField(max_length=30)
    repassword = models.CharField(max_length=30)
    gender = models.CharField(max_length=10, choices=[
                              ['male', 'Male'], ['female', 'Female']])
    dob = models.DateField()
    dor = models.DateTimeField(auto_now_add=True)

calls/forms.py
from django import forms
from calls.models import personal


class personal_form(forms.ModelForm):
    class Meta:
        model = personal
        fields = '__all__'  # ['username', 'email', 'phone']

calls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from calls.forms import personal_form
from calls.models import personal

# Create your views here.


def register(request):
    form = personal_form()  # generate the html content
    print(form)
    if request.method == 'POST':
        form = personal_form(request.POST)  # validation
        if form.is_valid:  # verify the data is valid or not
            # form.save()
            return HttpResponse("data is stored")
        else:
            return HttpResponse("data is not stored")
    return render(request=request, template_name="register.html", context={'form': form})


def update(request, pk):
    data = personal.objects.get(id=pk)
    print(data)
    form = personal_form(instance=data)  # generate the html content
    if request.method == 'POST':
        form = personal_form(request.POST, instance=data)  # validation
        if form.is_valid:  # verify the data is valid or not
            form.save()
            return HttpResponse("data is stored")
        else:
            return HttpResponse("data is not stored")
    return render(request=request, template_name="register.html", context={'form': form})


def list_details(request):
    res = personal.objects.all()
    return render(request=request, template_name='details.html', context={'data': res})


def delete(request, pk):
    try:
        res = personal.objects.get(id=pk)
        if request.method == "POST":
            res = personal.objects.get(id=pk).delete()
            return HttpResponse('data is deleted')
    except:
        res = None
    return render(request=request, template_name='delete.html', context={'id': res})


def hello(request):
    return HttpResponse("hello world")


def index(request):
    data = """
        <html>
        <head><title>index page</title></head>
        <body>
        <div>
        <h1>welcome to index page</h1>
        </div>
        </body>
        </html>"""
    return HttpResponse(data)


def home(request):
    return render(request=request, template_name="home.html")

whatsapp/views.py
from django.http import HttpResponse
from django.shortcuts import render


def login(request):
    class college:
        col_name = 'pys'

        def __init__(self, name, age, email):
            self.name = name
            self.age = age
            self.email = email

    return render(request=request, template_name='login.html',
                  context={'b': 100, 'a': True, 'li': ['a', 'b', 'c', 'hello'], 'di': {'x': 100, 'y': 500}, 'sai': college('sai', '26', 'sai@gmail.com')})


def upper_case(request, name):
    wish = f'''Hello,\n
     my dear {name.upper()},

     happy birthday to you.

     Thank you Dear. 
    '''
    return HttpResponse(wish)


def about(request, x, y):
    return render(request=request, template_name='about.html', context={'a': 'hello', 'b': y, 'l': [10, 200, 100, 50, 60], 'd': None})


def base(request, data):
    return render(request=request, template_name='base.html', context={'data': data.lower()})


def sample(request):
    d = [{'name': 'raja', 'email': 'raja@gmail.com', 'age': 26, 'phone': 9966885544},
         {'name': 'rani', 'email': 'rani@gmail.com',
             'age': 25, 'phone': 9966889998},
         {'name': 'dinga', 'email': 'dinga@gmail.com',
             'age': 24, 'phone': 8866885544},
         {'name': 'dingi', 'email': 'dingi@gmail.com',
             'age': 23, 'phone': 9976885544},
         {'name': 'ramu', 'email': 'ramu@gmail.com', 'age': 28, 'phone': 998885544}]
    return render(request=request, template_name='sample.html', context={'data': d})

calls/templates/delete.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>delete</title>
</head>

<body>
    {% if id %}
    <form action="" method="post">
        {%csrf_token%}
        <h1>Are you sure to delete id {{id.id}} data</h1>
        <h2>Username: {{id.username}}</h2>
        <input type="submit" value="Delete">
    </form>
    {% else %}
    <h1>data is not found </h1>
    {% endif %}

</body>

</html>

calls/templates/details.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    {% if data %}


    <table border="2">
        <tr>
            <th>Username</th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
            <th>Phone</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Update</th>
            <th>delete</th>
        </tr>
        {% for i in data%}
        <tr>
            <td>{{i.username}}</td>
            <td>{{i.firstname}}</td>
            <td>{{i.lastname}}</td>
            <td>{{i.email}}</td>
            <td>{{i.phone}}</td>
            <td>{{i.gender}}</td>
            <td>{{i.dob}}</td>
            <td><a href="{% url 'calls:update' pk=i.id %}"><button>Update</button></a></td>
            <td><a href="{% url 'calls:delete' pk=i.id %}"><button>delete</button></a></td>

        </tr>
        {% endfor %}
    </table>
    {% else %}
    <h1>data is not found</h1>
    {% endif %}
    <a href="{% url 'calls:register'%}"><button>Register</button></a>

</body>

</html>

calls/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>homepage</title>
</head>

<body>
    <h1>welcome to home page</h1>
    <marquee behavior="" direction="top">thank you</marquee>
</body>

</html>

calls/templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/register.css'%}">
</head>

<body>
    <div class="reg">
        <h1> Register Form</h1>
        <form action="" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <input type="submit" value="register">
        </form>
    </div>
</body>

</html>

templates/about.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <!-- <h1> hello</h1>
    <h2>variable a: {{a}}</h2>
    <h2>variable b: {{b}}</h2> -->
    {% if 100 %} <h1>"hello"</h1>

    {% endif %}

    <!-- {{ 'helloworld123' | add:"haii" }} -->
    <!-- {{10 | add:20}} -->
    {{'hello world haii'| title }}<br>
    {{'hello world haii'| upper }}<br>
    {{'hello world haii'| lower }}<br>
    {{'hello world haii'| wordcount }}<br>
    {{'hello world haii'| length }}<br>
    {{'hello \n world \n haii'| linenumbers }}<br>
    {{'hello \n world \n haii'| slice:'::-1' }}<br>
    {{'hello \n world \n haii'| first }}<br>
    {{'hello \n world \n haii'| last }}<br>
    {{'hello \n world \n haii'| join:"-" }}<br>
    {{d|default:'100'}}<br>
    {{'hello \n world \n haii'|cut:'10'}}<br>

    {{'hello \n world \n haii'|truncatewords:1}}<br>
    {{'hello \n world \n haii'|capfirst}}


</body>

</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1> welcome </h1>
    {%if data == 'register'%}
    <h1>fill the form</h1>
    <form action="" method="post">
        <label for="username">username</label><input type="text" name="username" id="username">
        <label for="firstname">firstname</label><input type="text" name="firstname" id="firstname">
        <label for="email">email</label><input type="email" name="email" id="email">
        <label for="phone">phone</label><input type="tel" name="phone" id="firstname">
        <label for="password">password</label><input type="password" name="password" id="firstname">
        <input type="submit" value="register">
    </form>
    {%elif data == 'login' %}
    <h1>login form</h1>
    <form action="" method="post">
        <label for="username">username</label><input type="text" name="username" id="username">
        <label for="password">password</label><input type="password" name="password" id="password">
        <input type="submit" value="login">
    </form>
    {%else%}
    <h1>sorry invalid input</h1>
    {% endif %}
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>variable: {{a}} </h1>
    <h1>variable: {{b}} </h1>
    <h1>list value: {{li}}</h1>
    <h1>ending list value: {{li.3}}</h1>
    <h1>ending list value: {{li.3.1}}</h1>
    <h1>starting list value: {{li.0}}</h1>
    <h1>dict value: {{di}}</h1>
    <h1>dict x value: {{di.x}}</h1>

    <h1>student data</h1>
    <hr>
    <h2>college name: {{sai.col_name}}</h2>
    <h2>student name: {{sai.name}}</h2>
    <h2>student age: {{sai.age}}</h2>
    <h2>student email: {{sai.email}}</h2>
</body>

</html>

templates/sample.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <table border="2">
        <tr>
            <th>Name</th>
            <th>age</th>
            <th>email</th>
            <th>phone</th>
        </tr>
        {% for i in data%}
        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.email}}</td>
        <td>{{i.phone}}</td>
        </tr>
        {% endfor %}
    </table>

</body>

</html>